#!/bin/bash

source fw_common.sh

# Define proper usage.
if [ -z ${2-} ]; then
	_fw_usage "ALIAS_NAME DNS [PORT] [PROTO]
	ALIAS_NAME is to be used in fw_rule.
	DNS is a FQDN which will be resolved for IPv4 and IPv6 by dig.
	PORT is a TCP or UDP port.
	PROTO is either tcp or udp, default is tcp."
else
	# PREFIX_IPSET will be added in fw_alias_ip.
	v_name="$1"; shift
	v_dns="$1"; shift
fi

dig_dns () {
	$DIG "$1" A +short
	$DIG "$1" AAAA +short
}

dig_dns "$v_dns" | while read v_ip
do
	[[ ${v_ip} =~ ^[0-9a-fA-F.:]+$ ]] || continue
	fw_alias_ip "$v_name" "$v_ip" "$@"
done

exit 0
