#!/bin/bash

# Variables
if [ -z "${VARS_SOURCED-}" ]; then
	export DEBUG=1
	export TRACE=0

	# Globals
	export _F=2
	export _NAME="cfirewalld"
	export _PROG="${0##*/}"
	export CACHEDIR=`mktemp -d /tmp/${_PROG}.XXXXXX`
	export COMMIT_FILE="/tmp/cfw_commit_in_progress"
	export CONNTRACK_ENABLED=1
	export DIR="$( cd "${BASH_SOURCE[0]%/*}" && pwd )"
	export FWD="CFWDEL_"
	export FWR="CFW_"
	export FWTMP="CFWTMP_"
	export IPTABLES_TABLES="filter nat mangle"
	export IPTABLES_CHAINS="prerouting postrouting input forward output"
	export LOG_SOCKET="/tmp/cfirewalld-log.socket"
	export PROG=${0##*/}
	export VARS_SOURCED=1
	# Global with deps
	export FAIL="$CACHEDIR/failed"
	export PATH=$DIR:$PATH

	# Programs. type -P is a builtin; which is not.
	export SUDO="$(type -P sudo)"
	export DIG="_run $(type -P dig)"
	export IPSET="_run $(type -P ipset)"
	export IP4TABLES="_run $(type -P iptables)"
	export IP6TABLES="_run $(type -P ip6tables)"
	export IP4TABLES_SAVE="_run $(type -P iptables-save)"
	export IP6TABLES_SAVE="_run $(type -P ip6tables-save)"

	# Runtime
	export RUNDIR=/run/${_NAME}
	export IPSET_PREFIX_FILE=$RUNDIR/ipset_prefix

	# Build helper. Set CFW_HELPER=0 to force the BASH build path.
	export CFW_HELPER="${CFW_HELPER-/usr/lib/cfirewalld/cfw-build}"
fi

. /etc/cfirewalld/fw_vars
